# Generated by Django 5.1.5 on 2025-02-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latency', models.FloatField()),
                ('packet_loss', models.FloatField()),
                ('jitter', models.FloatField()),
                ('label', models.CharField(choices=[('Normal', 'Normal'), ('Faulty', 'Faulty')], max_length=20)),
            ],
        ),
    ]
